# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: fa378b8ed33dd5e5d4d5857d1343a73c119aa9b1599297fa1da4ead5422d04f311cdadca60c804531f053425f13ae073072a29e26e743e685b7de0fdcef7ea24

test:
  secret_key_base: dedd775e1841912356ce45d0676106b2da3fff7056991454c0aebc4944f99147c7b93923bc62f751a6acd7be63b5813b3265ee3aed103bfbc929ec9f49f74dab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
